# Send debug messages
debug: false
doMobSpawns: true
spawnSearchRadius: 128
minChunkSpawnRad: 2
maxChunkSpawnRad: 7
maxSpawnAmount: 50
spawnTaskDelay: 500
mobCaps:
  passive: 10
  hostile: 20
  flying: 5