name: Publish Snapshot

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Load gradle cache
        uses: actions/cache@v1
        id: cache
        with:
          path: nms-build/.m2/repository
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install NMS
        if: steps.cache.outputs.cache-hit != 'true'
        uses: derongan/nmsaction@v1
        with:
          rev: 1.15
      - name: Install nms into m2
        run: mkdir -p $HOME/.m2/repository && cp -a nms-build/.m2/repository/. $HOME/.m2/repository
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          ./gradlew -PbuildNo=${{ github.run_number }} publish